int _putchar(char c);
char *_memset(char *s, char h, unsigned int n);
char *_memcpy(char *dest, char *src, unsigned int n);
char *_strchr(chr *s, char c);
unsigned int_strspn(char *s, char *accept);
char *_strpbrk(char *s, char accept);
char *_strstr(char *haystack, char *needle);
void print_chessboard(char (*a)[8]);
void print_diagsums(int *a, intsize);
void set_string(char **a, char *to);
